### ISSUE TITLE
[BE] Mail reset password

### ISSUE THREAD

**Issue by CloudSalander** [IT-Academy-BCN/ita-landing#82]

**Comment by CloudSalander** [comment]
- Verify if magent its the same color than frontend.
- Add explicit url for password reset on the email.
- Generate token for add it to the react app.
- Test mail sending in server.

**Comment by FranEnLaNube** [comment]
@CloudSalander Wasn't this Issue closed in #88?

**Comment by CloudSalander** [comment]
We have to update the hardcoded url of the reset-password link :)

Specifically to the domain https://it-academy-landing.netlify.app/

**Comment by CloudSalander** [comment]
Okey, we don't know if actually exists in prod environment the reset-password view. We will wait to @vicenlu confirmation.

**Comment by FranEnLaNube** [comment]
Great job @brycoti with your #103 to resolve #82! You are really welcomed in this project! 💯 
Let me add my approach to attack this problem in #108 .
I hope is good!
